apiVersion: v1
kind: Secret
metadata:
  name: fgtech-tls
  namespace: fgtech-system
  annotations:
    description: "Replace data with your TLS certificate"
type: kubernetes.io/tls
data:
  tls.crt: REPLACE_ME_BASE64_CERT
  tls.key: REPLACE_ME_BASE64_KEY
