apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fgteches.fgtech.fgtech.io
spec:
  group: fgtech.fgtech.io
  names:
    kind: Fgtech
    listKind: FgtechList
    plural: fgteches
    singular: fgtech
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - version
                - image
              properties:
                version:
                  type: string
                  description: Version to deploy
                image:
                  type: string
                  description: Container image reference
                path:
                  type: string
                  description: Optional URL path, defaults to resource name
          required:
            - spec
      additionalPrinterColumns:
        - name: Version
          type: string
          jsonPath: .spec.version
        - name: Image
          type: string
          jsonPath: .spec.image
        - name: Path
          type: string
          jsonPath: .spec.path
